### ISSUE TITLE
Thunderbird 78.4.2

### ISSUE THREAD

**Issue by samuelbernardo** [opto/nostalgy#10]
Receive this message aflter installing the extension:
Nostalgy is incompatible with Thunderbird 78.4.2.

**Comment by ebuchlin** [comment]
In the [original Nostalgy repository README](https://github.com/nostalgy/nostalgy), Alain Frisch recommends Nostalgy++ (also by opto, same Github than this opto/nostalgy), or Quick Folder Move (with a different interface). I tried Nostalgy++ with Thunderbird 78.5.0 and it worked.

**Comment by samuelbernardolip** [comment]
@ebuchlin thank you for the reference, I confirm that version is working with most recent version of Thunderbird.

**Comment by samuelbernardo** [comment]
Closing this issue since is solved with Nostalgy++.
