### ISSUE TITLE
does not work with TB 68.4.2

### ISSUE THREAD

**Issue by sebastian-boecker** [opto/nostalgy#5]
When I try to move a message, the selector/autocompletion boxes show up; I select the folder and then -- nothing. Message is not moved, not copied. I tried to assign a new key for moving, but that did not change the behavior. TB 68.4.2 on Windows 10.

**Comment by crsqq** [comment]
Unable to install w TB 68.4.2 (on macOS but don't think that makes a difference).

**Comment by opto** [comment]
@sebastian: works here on win10 home. The first box with history does not work. You need to press left arrow up arrow.
The second box after entering letters does work

@crsqq: installs here on win 10. You can try the new version, upload today.

**Comment by dkfarns** [comment]
I am having the same problem as crsqq with TB 68.4.2. on xubuntu 19.10

Updated 02-18:  I did manage to get it working.  It seems like finding the correct file on git hub (and possibly left clicking vs right clicking save-as) is a little confusing at the moment.

**Comment by sebastian-boecker** [comment]
Works again for me (**nostalgy1.0.25.xpi, Jan 19, 2020**, TB 68.5.0, Win 10), many thx. Issue can be closed from my side. Great tool! :)

**Comment by crsqq** [comment]
Installation works, again.

However, keyboard shortcuts don't work.

**Comment by caugner** [comment]
@crsqq Could you please try with the latest version from Thunderbird Add-ons: https://addons.thunderbird.net/thunderbird/addon/nostalgy/

**Comment by crsqq** [comment]
> @crsqq Could you please try with the latest version from Thunderbird Add-ons: https://addons.thunderbird.net/thunderbird/addon/nostalgy/

works.

**Comment by caugner** [comment]
Thanks.

@sebastian-boecker Would you mind closing this issue?
