### ISSUE TITLE
Beyond Thunderbird 68

### ISSUE THREAD

**Issue by wshanks** [opto/nostalgy#7]
https://github.com/nostalgy/nostalgy/issues/71 was locked, so I couldn't comment and I wasn't sure how else to communicate with you....

The problem of migrating addons was solved in Firefox with embedded WebExtensions: https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Embedded_WebExtensions. That may not be feasible for Thunderbird.

Is there any particular place where discussion of new Thunderbird WebExtensions API's is taking place? What I have found so far is a bit of discussion about the time frame for TB78 in the [tb-planning](https://groups.google.com/forum/#!forum/tb-planning) mailing list and some bugs marked as blocking [this WebExtensions meta-bug in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1396172). I don't see much in the discourse forums. (And of course there is [the Thunderbird WebExtensions documentation](https://thunderbird-webextensions.readthedocs.io/en/latest/index.html), but that just summarizes the current status without insight into what is planned or being worked on.

**Comment by caugner** [comment]
You might also want to check out https://github.com/nostalgy/nostalgy/issues/85.

**Comment by opto** [comment]
I just put in a few more hours for preparing 78. (10 hours or more?). It's still too early, webextensions are too broken. Getting a menuitem into tools menu? Nope, permitted only in FF, but not by TB team. Putting a menu in some other allowed place? Nope, broken, doesn't work yet. Tried a few other things that are needed but not working yet.

I think the webextension apis just need mor time to get finished. They are still work in progress.

But I am onto it,

Klaus

**Comment by r2evans** [comment]
I've not heard good words about WebExtensions on other addons, and silence here does not bode well either. Any thoughts or progress? (I'm not rushing, I understand it's strong effort for non-payment.)

Thanks!

**Comment by wshanks** [comment]
I think the focus should be at https://github.com/nostalgy/nostalgy/issues/85 rather than here. I opened this issue because I didn't know of an alternative for asking opto about his plans for 78. Anecdotally, I can say that I ported one addon to Thunderbird 78 and it wasn't too bad. I just stuffed it into a WebExtension experiment and luckily no internal Thunderbird features I was using changed between 68 and 78. A larger, older addon like nostalgy probably has to deal with more old internal XUL API's breaking though.

**Comment by r2evans** [comment]
Thank you, @willsALMANJ. (That's good news!)

I had assumed that opto forked from nostalgy/nostalgy because Alain was no longer able to devote time to it. On which repo is development being done? (This might be more of a question for @opto ...)

**Comment by wshanks** [comment]
If I remember correctly, the repo was moved from Alain's account to nostalgy/nostalgy to indicate that development was shared among more people now. I think Alain might still control the addons.thunderbird.net listing but opto and a few other people (the ones posting on https://github.com/nostalgy/nostalgy/issues/85) are working on the port to 78. I don't know if the porting work in progress is in a public repo or just on local branches for now.
